import prisma from './prisma';
import { DetectionRule, Event } from '@prisma/client';

/**
 * Evaluates a newly ingested event against active detection rules.
 * Generates an Alert record if any rule triggers.
 */
export async function runDetectionEngine(newEvent: Event) {
  try {
    // Ensure DB is initialized (run seeding check dynamically)
    // Query active rules matching the event type
    const activeRules = await prisma.detectionRule.findMany({
      where: {
        eventType: newEvent.eventType,
        isActive: true,
      },
    });

    for (const rule of activeRules) {
      // Case A: Single-event pattern rules (threshold = 1, timeWindow = 0) (FR-3.4)
      if (rule.threshold <= 1 && rule.timeWindow === 0) {
        await triggerAlert(rule, newEvent);
        continue;
      }

      // Case B: Threshold-based rules within a time window (FR-3.3)
      // Find events of this type from the same source in the window
      const windowStart = new Date(Date.now() - rule.timeWindow * 1000);
      const matchingEventsCount = await prisma.event.count({
        where: {
          eventType: rule.eventType,
          sourceId: newEvent.sourceId,
          receivedAt: {
            gte: windowStart,
          },
        },
      });

      if (matchingEventsCount >= rule.threshold) {
        await triggerAlert(rule, newEvent);
      }
    }
  } catch (error) {
    console.error('Error in detection engine execution:', error);
  }
}

/**
 * Triggers and records an alert for a matched rule.
 */
async function triggerAlert(rule: DetectionRule, event: Event) {
  // Check to avoid double alerting the same rule on the exact same event
  const alertExists = await prisma.alert.findFirst({
    where: {
      ruleName: rule.name,
      eventId: event.id,
    },
  });

  if (alertExists) return;

  // Create alert record (FR-4.1, FR-4.2)
  const newAlert = await prisma.alert.create({
    data: {
      ruleName: rule.name,
      severity: rule.severity,
      status: 'NEW',
      eventId: event.id,
      notes: `Rule triggered due to event type: "${rule.eventType}". Description: ${rule.description}`,
    },
  });

  // Write system audit log (FR-7.1)
  await prisma.auditLog.create({
    data: {
      action: 'ALERT_GENERATED',
      details: `Alert ID: ${newAlert.id} generated by rule "${rule.name}" on event ID: ${event.id}`,
    },
  });

  console.log(`Alert triggered: ${rule.name} (Severity: ${rule.severity})`);
}
